import { FigureContent } from './news-figure-schema.js'

// Isolated component specimens, never ingested, commissioned, or published as news.
const base={afterParagraph:1,caption:'Illustrative component test data, not real-world observations or reporting.'}
export const visualExamples=[
  {id:'sample-line',kind:'line',title:'A trend, a gap, a turning point',xLabel:'Observation date',yLabel:'Activity',xUnit:'UTC',yUnit:'index',xFormat:'date',yBaseline:'zero',series:[{label:'Series A',points:[{x:Date.UTC(2026,0,1),y:28},{x:Date.UTC(2026,1,1),y:35},{x:Date.UTC(2026,2,1),y:null},{x:Date.UTC(2026,3,1),y:48},{x:Date.UTC(2026,4,1),y:42},{x:Date.UTC(2026,5,1),y:58}]},{label:'Series B',points:[{x:Date.UTC(2026,0,1),y:44},{x:Date.UTC(2026,2,1),y:38},{x:Date.UTC(2026,5,1),y:30}]}],annotations:[{series:'Series A',pointIndex:4,text:'An annotation anchored to an actual point; the March observation is deliberately missing.'}]},
  {id:'sample-scatter',kind:'scatter',title:'The relationship, not just the ranking',xLabel:'Cost',yLabel:'Performance',xUnit:'test units',yUnit:'test points',period:'Synthetic comparison',sizeUnit:'sample size',points:[{label:'A',x:15,y:28,size:20,group:'Group 1'},{label:'B',x:30,y:57,size:80,group:'Group 1'},{label:'C',x:44,y:48,size:40,group:'Group 2'},{label:'D',x:57,y:77,size:140,group:'Group 2'},{label:'E',x:80,y:68,size:60,group:'Group 1'}]},
  {id:'sample-stacked',kind:'stacked',title:'One total, several contributors',unit:'test units',period:'Synthetic comparison',mode:'share',segments:['Core','Services','Other'],rows:[{label:'Group A',values:[45,30,25],note:'Each row is normalized; its original total is still shown.'},{label:'Group B',values:[20,15,5],note:''},{label:'Group C',values:[10,55,15],note:''}]},
  {id:'sample-waterfall',kind:'waterfall',title:'What changed between the two totals',unit:'test units',period:'Synthetic bridge',start:{label:'Starting value',value:80},changes:[{label:'Volume',value:28},{label:'Pricing',value:14},{label:'Costs',value:-37}],endLabel:'Ending value'},
  {id:'sample-heatmap',kind:'heatmap',title:'Where change is concentrated',unit:'test points',period:'Synthetic matrix',xLabels:['A','B','C','D'],yLabels:['First','Second','Third'],values:[[12,-8,0,null],[4,18,-11,6],[-7,2,9,15]]},
  {id:'sample-map',kind:'map',title:'Places in a connected story',region:'world',points:[{label:'New York',lat:40.71,lng:-74.01,detail:'A locator specimen, not an economic statistic.'},{label:'Paris',lat:48.86,lng:2.35,detail:'Tap or focus a marker; no private map provider or external image request.'},{label:'Shanghai',lat:31.23,lng:121.47,detail:'Coordinates orient the reader. Marker size carries no quantitative meaning.'}]},
  {id:'sample-network',kind:'network',title:'Who depends on whom',directed:true,nodes:[{id:'research',label:'Research',detail:'Develops a reusable capability.'},{id:'product',label:'Product',detail:'Turns capability into a repeatable workflow.'},{id:'customer',label:'Customer',detail:'Uses the workflow in a real setting.'},{id:'deployment',label:'Deployment',detail:'Adapts the workflow and relays constraints.'}],edges:[{from:'research',to:'product',label:'Provides capability'},{from:'product',to:'customer',label:'Delivers a workflow'},{from:'customer',to:'deployment',label:'Reveals requirements'},{from:'deployment',to:'product',label:'Supplies feedback'}]},
  {id:'sample-comparison',kind:'comparison',title:'Different questions, different measures',columns:['What it captures','What it cannot establish'],rows:[{label:'Quantity','values':['How much is present','Whether it is useful']},{label:'Change',values:['The difference between observations','Why the change happened']},{label:'Distribution',values:['How observations differ','A causal explanation']}]},
  {id:'sample-bars',kind:'bars',title:'Gains and losses on the same scale',unit:'test units',period:'Synthetic comparison',rows:[{label:'A',value:24,note:''},{label:'B',value:-9,note:''},{label:'C',value:0,note:'Zero is an observation, not missing data.'}]},
  {id:'sample-flow',kind:'flow',title:'The constraint between two decisions',steps:[{label:'Request',detail:'A request enters the process.'},{label:'Check',detail:'A requirement must be satisfied.'},{label:'Decision',detail:'An outcome follows the stated rule.'}]},
  {id:'sample-timeline',kind:'timeline',title:'An announcement is not implementation',steps:[{label:'Day one',detail:'A proposal is announced.'},{label:'Day five',detail:'A formal decision is made.'},{label:'Day twenty',detail:'The decision takes effect.'}]},
].map(value=>FigureContent.parse({...base,...value}))
